// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/yaredow/glimpse-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockgenreLister is an autogenerated mock type for the genreLister type
type MockgenreLister struct {
	mock.Mock
}

type MockgenreLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockgenreLister) EXPECT() *MockgenreLister_Expecter {
	return &MockgenreLister_Expecter{mock: &_m.Mock}
}

// ListAllGenres provides a mock function with given fields: ctx
func (_m *MockgenreLister) ListAllGenres(ctx context.Context) ([]domain.Genre, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllGenres")
	}

	var r0 []domain.Genre
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Genre, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Genre); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Genre)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockgenreLister_ListAllGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllGenres'
type MockgenreLister_ListAllGenres_Call struct {
	*mock.Call
}

// ListAllGenres is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockgenreLister_Expecter) ListAllGenres(ctx interface{}) *MockgenreLister_ListAllGenres_Call {
	return &MockgenreLister_ListAllGenres_Call{Call: _e.mock.On("ListAllGenres", ctx)}
}

func (_c *MockgenreLister_ListAllGenres_Call) Run(run func(ctx context.Context)) *MockgenreLister_ListAllGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockgenreLister_ListAllGenres_Call) Return(_a0 []domain.Genre, _a1 error) *MockgenreLister_ListAllGenres_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockgenreLister_ListAllGenres_Call) RunAndReturn(run func(context.Context) ([]domain.Genre, error)) *MockgenreLister_ListAllGenres_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockgenreLister creates a new instance of MockgenreLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockgenreLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockgenreLister {
	mock := &MockgenreLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
