// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/yaredow/glimpse-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: ctx, tokenPlainText
func (_m *UserService) Activate(ctx context.Context, tokenPlainText string) (*domain.User, error) {
	ret := _m.Called(ctx, tokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, tokenPlainText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, tokenPlainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenPlainText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type UserService_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenPlainText string
func (_e *UserService_Expecter) Activate(ctx interface{}, tokenPlainText interface{}) *UserService_Activate_Call {
	return &UserService_Activate_Call{Call: _e.mock.On("Activate", ctx, tokenPlainText)}
}

func (_c *UserService_Activate_Call) Run(run func(ctx context.Context, tokenPlainText string)) *UserService_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_Activate_Call) Return(_a0 *domain.User, _a1 error) *UserService_Activate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_Activate_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserService_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function with given fields: ctx, email, password
func (_m *UserService) Authenticate(ctx context.Context, email string, password string) (*domain.User, *domain.RefreshToken, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.User
	var r1 *domain.RefreshToken
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, *domain.RefreshToken, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *domain.RefreshToken); ok {
		r1 = rf(ctx, email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type UserService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *UserService_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *UserService_Authenticate_Call {
	return &UserService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *UserService_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *UserService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserService_Authenticate_Call) Return(_a0 *domain.User, _a1 *domain.RefreshToken, _a2 error) *UserService_Authenticate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserService_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, *domain.RefreshToken, error)) *UserService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserService) Create(ctx context.Context, user *domain.User) (*domain.Token, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.Token, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.Token); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *UserService_Expecter) Create(ctx interface{}, user interface{}) *UserService_Create_Call {
	return &UserService_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserService_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *UserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *UserService_Create_Call) Return(_a0 *domain.Token, _a1 error) *UserService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_Create_Call) RunAndReturn(run func(context.Context, *domain.User) (*domain.Token, error)) *UserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserService) GetByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserService_Expecter) GetByID(ctx interface{}, id interface{}) *UserService_GetByID_Call {
	return &UserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserService_GetByID_Call) Run(run func(ctx context.Context, id int64)) *UserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserService_GetByID_Call) Return(_a0 *domain.User, _a1 error) *UserService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*domain.User, error)) *UserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function with given fields: ctx, email
func (_m *UserService) RequestPasswordReset(ctx context.Context, email string) (*domain.Token, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Token, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Token); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type UserService_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *UserService_RequestPasswordReset_Call {
	return &UserService_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *UserService_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *UserService_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_RequestPasswordReset_Call) Return(_a0 *domain.Token, _a1 error) *UserService_RequestPasswordReset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_RequestPasswordReset_Call) RunAndReturn(run func(context.Context, string) (*domain.Token, error)) *UserService_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, tokenPlainText, newPassword
func (_m *UserService) ResetPassword(ctx context.Context, tokenPlainText string, newPassword string) error {
	ret := _m.Called(ctx, tokenPlainText, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tokenPlainText, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type UserService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenPlainText string
//   - newPassword string
func (_e *UserService_Expecter) ResetPassword(ctx interface{}, tokenPlainText interface{}, newPassword interface{}) *UserService_ResetPassword_Call {
	return &UserService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, tokenPlainText, newPassword)}
}

func (_c *UserService_ResetPassword_Call) Run(run func(ctx context.Context, tokenPlainText string, newPassword string)) *UserService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UserService_ResetPassword_Call) Return(_a0 error) *UserService_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_ResetPassword_Call) RunAndReturn(run func(context.Context, string, string) error) *UserService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, refreshTokenPlainText
func (_m *UserService) RevokeRefreshToken(ctx context.Context, refreshTokenPlainText string) error {
	ret := _m.Called(ctx, refreshTokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshTokenPlainText)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type UserService_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenPlainText string
func (_e *UserService_Expecter) RevokeRefreshToken(ctx interface{}, refreshTokenPlainText interface{}) *UserService_RevokeRefreshToken_Call {
	return &UserService_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, refreshTokenPlainText)}
}

func (_c *UserService_RevokeRefreshToken_Call) Run(run func(ctx context.Context, refreshTokenPlainText string)) *UserService_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_RevokeRefreshToken_Call) Return(_a0 error) *UserService_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *UserService_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RotateRefreshToken provides a mock function with given fields: ctx, refreshTokenPlainText
func (_m *UserService) RotateRefreshToken(ctx context.Context, refreshTokenPlainText string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, refreshTokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for RotateRefreshToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, refreshTokenPlainText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, refreshTokenPlainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshTokenPlainText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_RotateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateRefreshToken'
type UserService_RotateRefreshToken_Call struct {
	*mock.Call
}

// RotateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenPlainText string
func (_e *UserService_Expecter) RotateRefreshToken(ctx interface{}, refreshTokenPlainText interface{}) *UserService_RotateRefreshToken_Call {
	return &UserService_RotateRefreshToken_Call{Call: _e.mock.On("RotateRefreshToken", ctx, refreshTokenPlainText)}
}

func (_c *UserService_RotateRefreshToken_Call) Run(run func(ctx context.Context, refreshTokenPlainText string)) *UserService_RotateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_RotateRefreshToken_Call) Return(_a0 *domain.RefreshToken, _a1 error) *UserService_RotateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_RotateRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *UserService_RotateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
