version: 3
workdir: internal

allow:
  depOnAnyVendor: false
  deepScan: true

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\\/mocks\\/.*$"

vendors:
  echo:
    in:
      - github.com/labstack/echo/v5
      - github.com/labstack/echo/v5/**
  pgx:
    in:
      - github.com/jackc/pgx/v5
      - github.com/jackc/pgx/v5/**
  crypto:
    in: golang.org/x/crypto/**

components:
  handler:     { in: handler/** }
  service:     { in: service/** }
  repository:  { in: repository/** }
  domain:      { in: domain }

commonComponents:
  - domain

deps:
  handler:
    mayDependOn:
      - service
    canUse:
      - echo

  service:
    mayDependOn:
      - repository
    canUse:
      - crypto

  repository:
    mayDependOn:
      - repository
    canUse:
      - pgx
