// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate.sql

package queries

import (
	"context"
)

const getCandidateMovies = `-- name: GetCandidateMovies :many
SELECT m.id, m.tmdb_id, m.imdb_id, m.vague_description, m.genres, m.title, m.original_title, m.full_synopsis, m.poster_path, m.backdrop_path, m.release_date, m.runtime, m.vote_average, m.vote_count, m.original_language, m.popularity, m.created_at, m.shown_count, m.watched_count, m.global_watch_rate, m.tagline, m.director, m.cast_members, m.trailer_key, m.spoken_languages, m.production_countries, m.detail_synced_at FROM movies m
WHERE m.id NOT IN (
	SELECT movie_id FROM user_interactions
	WHERE user_interactions.user_id = $1 AND action IN ('watched', 'skipped')
	) AND (
		EXISTS (
			SELECT 1 FROM user_affinities a
			WHERE a.user_id = $1 AND a.dimension = 'genre'
				AND a.value = ANY(m.genres) AND a.score > 0
		)
		OR NOT EXISTS (SELECT 1 FROM user_affinities WHERE user_id = $1)
)
ORDER BY m.popularity DESC
LIMIT $2
`

type GetCandidateMoviesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetCandidateMovies(ctx context.Context, arg GetCandidateMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getCandidateMovies, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.ImdbID,
			&i.VagueDescription,
			&i.Genres,
			&i.Title,
			&i.OriginalTitle,
			&i.FullSynopsis,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ReleaseDate,
			&i.Runtime,
			&i.VoteAverage,
			&i.VoteCount,
			&i.OriginalLanguage,
			&i.Popularity,
			&i.CreatedAt,
			&i.ShownCount,
			&i.WatchedCount,
			&i.GlobalWatchRate,
			&i.Tagline,
			&i.Director,
			&i.CastMembers,
			&i.TrailerKey,
			&i.SpokenLanguages,
			&i.ProductionCountries,
			&i.DetailSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
