// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preference.sql

package queries

import (
	"context"
)

const getUserPreference = `-- name: GetUserPreference :one
SELECT user_id, favorite_genres, excluded_genres, languages, min_rating, onboarded, created_at, updated_at, min_year, max_year FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreference(ctx context.Context, userID int64) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreference, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.FavoriteGenres,
		&i.ExcludedGenres,
		&i.Languages,
		&i.MinRating,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinYear,
		&i.MaxYear,
	)
	return i, err
}

const updateOnboardingStatus = `-- name: UpdateOnboardingStatus :exec
UPDATE user_preferences SET onboarded = $2, updated_at = NOW() WHERE user_id = $1
`

type UpdateOnboardingStatusParams struct {
	UserID    int64 `json:"user_id"`
	Onboarded bool  `json:"onboarded"`
}

func (q *Queries) UpdateOnboardingStatus(ctx context.Context, arg UpdateOnboardingStatusParams) error {
	_, err := q.db.Exec(ctx, updateOnboardingStatus, arg.UserID, arg.Onboarded)
	return err
}

const upsertPreference = `-- name: UpsertPreference :one
INSERT INTO user_preferences (user_id, favorite_genres, excluded_genres, languages, min_rating, onboarded, min_year, max_year)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE 
SET 
    favorite_genres = EXCLUDED.favorite_genres,
    excluded_genres = EXCLUDED.excluded_genres,
    languages = EXCLUDED.languages,
    min_rating = EXCLUDED.min_rating,
    onboarded = EXCLUDED.onboarded,
    min_year = EXCLUDED.min_year,
    max_year = EXCLUDED.max_year,
    updated_at = NOW()
RETURNING user_id, favorite_genres, excluded_genres, languages, min_rating, onboarded, created_at, updated_at, min_year, max_year
`

type UpsertPreferenceParams struct {
	UserID         int64    `json:"user_id"`
	FavoriteGenres []int32  `json:"favorite_genres"`
	ExcludedGenres []int32  `json:"excluded_genres"`
	Languages      []string `json:"languages"`
	MinRating      float64  `json:"min_rating"`
	Onboarded      bool     `json:"onboarded"`
	MinYear        int32    `json:"min_year"`
	MaxYear        int32    `json:"max_year"`
}

func (q *Queries) UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertPreference,
		arg.UserID,
		arg.FavoriteGenres,
		arg.ExcludedGenres,
		arg.Languages,
		arg.MinRating,
		arg.Onboarded,
		arg.MinYear,
		arg.MaxYear,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.FavoriteGenres,
		&i.ExcludedGenres,
		&i.Languages,
		&i.MinRating,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MinYear,
		&i.MaxYear,
	)
	return i, err
}
