// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_grid_history.sql

package queries

import (
	"context"
	"time"
)

const cleanupOldGridHistory = `-- name: CleanupOldGridHistory :exec
DELETE FROM user_grid_history
WHERE shown_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupOldGridHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldGridHistory)
	return err
}

const getRecentlyShownMovies = `-- name: GetRecentlyShownMovies :many
SELECT
    movie_id,
    shown_at
FROM user_grid_history
WHERE user_id = $1
ORDER BY shown_at DESC
LIMIT $2
`

type GetRecentlyShownMoviesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentlyShownMoviesRow struct {
	MovieID int64     `json:"movie_id"`
	ShownAt time.Time `json:"shown_at"`
}

func (q *Queries) GetRecentlyShownMovies(ctx context.Context, arg GetRecentlyShownMoviesParams) ([]GetRecentlyShownMoviesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyShownMovies, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentlyShownMoviesRow{}
	for rows.Next() {
		var i GetRecentlyShownMoviesRow
		if err := rows.Scan(&i.MovieID, &i.ShownAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGridHistory = `-- name: InsertGridHistory :exec
INSERT INTO user_grid_history (
    user_id, movie_id, shown_at
)
VALUES ($1, $2, NOW())
`

type InsertGridHistoryParams struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}

func (q *Queries) InsertGridHistory(ctx context.Context, arg InsertGridHistoryParams) error {
	_, err := q.db.Exec(ctx, insertGridHistory, arg.UserID, arg.MovieID)
	return err
}
