// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/yaredow/glimpse-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockpreferenceUpserter is an autogenerated mock type for the preferenceUpserter type
type MockpreferenceUpserter struct {
	mock.Mock
}

type MockpreferenceUpserter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockpreferenceUpserter) EXPECT() *MockpreferenceUpserter_Expecter {
	return &MockpreferenceUpserter_Expecter{mock: &_m.Mock}
}

// Upsert provides a mock function with given fields: ctx, p
func (_m *MockpreferenceUpserter) Upsert(ctx context.Context, p *domain.Preference) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Preference) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockpreferenceUpserter_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockpreferenceUpserter_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Preference
func (_e *MockpreferenceUpserter_Expecter) Upsert(ctx interface{}, p interface{}) *MockpreferenceUpserter_Upsert_Call {
	return &MockpreferenceUpserter_Upsert_Call{Call: _e.mock.On("Upsert", ctx, p)}
}

func (_c *MockpreferenceUpserter_Upsert_Call) Run(run func(ctx context.Context, p *domain.Preference)) *MockpreferenceUpserter_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Preference))
	})
	return _c
}

func (_c *MockpreferenceUpserter_Upsert_Call) Return(_a0 error) *MockpreferenceUpserter_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockpreferenceUpserter_Upsert_Call) RunAndReturn(run func(context.Context, *domain.Preference) error) *MockpreferenceUpserter_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockpreferenceUpserter creates a new instance of MockpreferenceUpserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockpreferenceUpserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockpreferenceUpserter {
	mock := &MockpreferenceUpserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
