// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mockonboarder is an autogenerated mock type for the onboarder type
type Mockonboarder struct {
	mock.Mock
}

type Mockonboarder_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockonboarder) EXPECT() *Mockonboarder_Expecter {
	return &Mockonboarder_Expecter{mock: &_m.Mock}
}

// UpdateOnboarded provides a mock function with given fields: ctx, userID, onboarded
func (_m *Mockonboarder) UpdateOnboarded(ctx context.Context, userID int64, onboarded bool) error {
	ret := _m.Called(ctx, userID, onboarded)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOnboarded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = rf(ctx, userID, onboarded)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mockonboarder_UpdateOnboarded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOnboarded'
type Mockonboarder_UpdateOnboarded_Call struct {
	*mock.Call
}

// UpdateOnboarded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - onboarded bool
func (_e *Mockonboarder_Expecter) UpdateOnboarded(ctx interface{}, userID interface{}, onboarded interface{}) *Mockonboarder_UpdateOnboarded_Call {
	return &Mockonboarder_UpdateOnboarded_Call{Call: _e.mock.On("UpdateOnboarded", ctx, userID, onboarded)}
}

func (_c *Mockonboarder_UpdateOnboarded_Call) Run(run func(ctx context.Context, userID int64, onboarded bool)) *Mockonboarder_UpdateOnboarded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(bool))
	})
	return _c
}

func (_c *Mockonboarder_UpdateOnboarded_Call) Return(_a0 error) *Mockonboarder_UpdateOnboarded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mockonboarder_UpdateOnboarded_Call) RunAndReturn(run func(context.Context, int64, bool) error) *Mockonboarder_UpdateOnboarded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockonboarder creates a new instance of Mockonboarder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockonboarder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockonboarder {
	mock := &Mockonboarder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
