// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaredow/glimpse-api/internal/domain"
)

// MockPreferenceRepository is an autogenerated mock type for the PreferenceRepository type
type MockPreferenceRepository struct {
	mock.Mock
}

type MockPreferenceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPreferenceRepository) EXPECT() *MockPreferenceRepository_Expecter {
	return &MockPreferenceRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockPreferenceRepository) GetByUserID(ctx context.Context, userID int64) (*domain.Preference, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Preference, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Preference); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Preference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPreferenceRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockPreferenceRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockPreferenceRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockPreferenceRepository_GetByUserID_Call {
	return &MockPreferenceRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockPreferenceRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockPreferenceRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockPreferenceRepository_GetByUserID_Call) Return(_a0 *domain.Preference, _a1 error) *MockPreferenceRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPreferenceRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, int64) (*domain.Preference, error)) *MockPreferenceRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, p
func (_m *MockPreferenceRepository) Upsert(ctx context.Context, p *domain.Preference) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Preference) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPreferenceRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockPreferenceRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Preference
func (_e *MockPreferenceRepository_Expecter) Upsert(ctx interface{}, p interface{}) *MockPreferenceRepository_Upsert_Call {
	return &MockPreferenceRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, p)}
}

func (_c *MockPreferenceRepository_Upsert_Call) Run(run func(ctx context.Context, p *domain.Preference)) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Preference))
	})
	return _c
}

func (_c *MockPreferenceRepository_Upsert_Call) Return(_a0 error) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPreferenceRepository_Upsert_Call) RunAndReturn(run func(context.Context, *domain.Preference) error) *MockPreferenceRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPreferenceRepository creates a new instance of MockPreferenceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreferenceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreferenceRepository {
	mock := &MockPreferenceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
