// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaredow/glimpse-api/internal/domain"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) DeleteAllForUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForUser'
type MockRefreshTokenRepository_DeleteAllForUser_Call struct {
	*mock.Call
}

// DeleteAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) DeleteAllForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	return &MockRefreshTokenRepository_DeleteAllForUser_Call{Call: _e.mock.On("DeleteAllForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) Run(run func(ctx context.Context, userID int64)) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) RunAndReturn(run func(context.Context, int64) error) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPlainText provides a mock function with given fields: ctx, refreshTokenPlainText
func (_m *MockRefreshTokenRepository) GetByPlainText(ctx context.Context, refreshTokenPlainText string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, refreshTokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlainText")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, refreshTokenPlainText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, refreshTokenPlainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshTokenPlainText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetByPlainText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPlainText'
type MockRefreshTokenRepository_GetByPlainText_Call struct {
	*mock.Call
}

// GetByPlainText is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenPlainText string
func (_e *MockRefreshTokenRepository_Expecter) GetByPlainText(ctx interface{}, refreshTokenPlainText interface{}) *MockRefreshTokenRepository_GetByPlainText_Call {
	return &MockRefreshTokenRepository_GetByPlainText_Call{Call: _e.mock.On("GetByPlainText", ctx, refreshTokenPlainText)}
}

func (_c *MockRefreshTokenRepository_GetByPlainText_Call) Run(run func(ctx context.Context, refreshTokenPlainText string)) *MockRefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetByPlainText_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetByPlainText_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Insert(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRefreshTokenRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Insert(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Insert_Call {
	return &MockRefreshTokenRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Insert_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Insert_Call) Return(_a0 error) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Insert_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByFamily provides a mock function with given fields: ctx, familyID
func (_m *MockRefreshTokenRepository) RevokeByFamily(ctx context.Context, familyID string) error {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByFamily'
type MockRefreshTokenRepository_RevokeByFamily_Call struct {
	*mock.Call
}

// RevokeByFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
func (_e *MockRefreshTokenRepository_Expecter) RevokeByFamily(ctx interface{}, familyID interface{}) *MockRefreshTokenRepository_RevokeByFamily_Call {
	return &MockRefreshTokenRepository_RevokeByFamily_Call{Call: _e.mock.On("RevokeByFamily", ctx, familyID)}
}

func (_c *MockRefreshTokenRepository_RevokeByFamily_Call) Run(run func(ctx context.Context, familyID string)) *MockRefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByFamily_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByFamily_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByHash provides a mock function with given fields: ctx, hash
func (_m *MockRefreshTokenRepository) RevokeByHash(ctx context.Context, hash []byte) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type MockRefreshTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *MockRefreshTokenRepository_Expecter) RevokeByHash(ctx interface{}, hash interface{}) *MockRefreshTokenRepository_RevokeByHash_Call {
	return &MockRefreshTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", ctx, hash)}
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) Run(run func(ctx context.Context, hash []byte)) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByHash_Call) RunAndReturn(run func(context.Context, []byte) error) *MockRefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, oldRefreshToken, newRefreshToken
func (_m *MockRefreshTokenRepository) Rotate(ctx context.Context, oldRefreshToken *domain.RefreshToken, newRefreshToken *domain.RefreshToken) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, oldRefreshToken, newRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) (*domain.RefreshToken, error)); ok {
		return rf(ctx, oldRefreshToken, newRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) *domain.RefreshToken); ok {
		r0 = rf(ctx, oldRefreshToken, newRefreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) error); ok {
		r1 = rf(ctx, oldRefreshToken, newRefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type MockRefreshTokenRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - oldRefreshToken *domain.RefreshToken
//   - newRefreshToken *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Rotate(ctx interface{}, oldRefreshToken interface{}, newRefreshToken interface{}) *MockRefreshTokenRepository_Rotate_Call {
	return &MockRefreshTokenRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, oldRefreshToken, newRefreshToken)}
}

func (_c *MockRefreshTokenRepository_Rotate_Call) Run(run func(ctx context.Context, oldRefreshToken *domain.RefreshToken, newRefreshToken *domain.RefreshToken)) *MockRefreshTokenRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken), args[2].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Rotate_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_Rotate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_Rotate_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken, *domain.RefreshToken) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOnboarded provides a mock function with given fields: ctx, userID, onboarded
func (_m *MockRefreshTokenRepository) UpdateOnboarded(ctx context.Context, userID string, onboarded bool) error {
	ret := _m.Called(ctx, userID, onboarded)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOnboarded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, userID, onboarded)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_UpdateOnboarded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOnboarded'
type MockRefreshTokenRepository_UpdateOnboarded_Call struct {
	*mock.Call
}

// UpdateOnboarded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - onboarded bool
func (_e *MockRefreshTokenRepository_Expecter) UpdateOnboarded(ctx interface{}, userID interface{}, onboarded interface{}) *MockRefreshTokenRepository_UpdateOnboarded_Call {
	return &MockRefreshTokenRepository_UpdateOnboarded_Call{Call: _e.mock.On("UpdateOnboarded", ctx, userID, onboarded)}
}

func (_c *MockRefreshTokenRepository_UpdateOnboarded_Call) Run(run func(ctx context.Context, userID string, onboarded bool)) *MockRefreshTokenRepository_UpdateOnboarded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_UpdateOnboarded_Call) Return(_a0 error) *MockRefreshTokenRepository_UpdateOnboarded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_UpdateOnboarded_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockRefreshTokenRepository_UpdateOnboarded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
