// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaredow/glimpse-api/internal/domain"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) DeleteAllForUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_DeleteAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForUser'
type MockRefreshTokenRepository_DeleteAllForUser_Call struct {
	*mock.Call
}

// DeleteAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRefreshTokenRepository_Expecter) DeleteAllForUser(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	return &MockRefreshTokenRepository_DeleteAllForUser_Call{Call: _e.mock.On("DeleteAllForUser", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) Run(run func(ctx context.Context, userID int64)) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) Return(_a0 error) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_DeleteAllForUser_Call) RunAndReturn(run func(context.Context, int64) error) *MockRefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Insert(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRefreshTokenRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Insert(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Insert_Call {
	return &MockRefreshTokenRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Insert_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Insert_Call) Return(_a0 error) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Insert_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
