// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaredow/glimpse-api/internal/domain"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllForUser provides a mock function with given fields: ctx, scope, userID
func (_m *MockTokenRepository) DeleteAllForUser(ctx context.Context, scope string, userID int64) error {
	ret := _m.Called(ctx, scope, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, scope, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_DeleteAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForUser'
type MockTokenRepository_DeleteAllForUser_Call struct {
	*mock.Call
}

// DeleteAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - userID int64
func (_e *MockTokenRepository_Expecter) DeleteAllForUser(ctx interface{}, scope interface{}, userID interface{}) *MockTokenRepository_DeleteAllForUser_Call {
	return &MockTokenRepository_DeleteAllForUser_Call{Call: _e.mock.On("DeleteAllForUser", ctx, scope, userID)}
}

func (_c *MockTokenRepository_DeleteAllForUser_Call) Run(run func(ctx context.Context, scope string, userID int64)) *MockTokenRepository_DeleteAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockTokenRepository_DeleteAllForUser_Call) Return(_a0 error) *MockTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_DeleteAllForUser_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) Insert(ctx context.Context, token *domain.Token) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Token) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTokenRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.Token
func (_e *MockTokenRepository_Expecter) Insert(ctx interface{}, token interface{}) *MockTokenRepository_Insert_Call {
	return &MockTokenRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, token)}
}

func (_c *MockTokenRepository_Insert_Call) Run(run func(ctx context.Context, token *domain.Token)) *MockTokenRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Token))
	})
	return _c
}

func (_c *MockTokenRepository_Insert_Call) Return(_a0 error) *MockTokenRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Insert_Call) RunAndReturn(run func(context.Context, *domain.Token) error) *MockTokenRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
