// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaredow/glimpse-api/internal/domain"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteAllForUser provides a mock function with given fields: ctx, userID
func (_m *RefreshTokenRepository) DeleteAllForUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_DeleteAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForUser'
type RefreshTokenRepository_DeleteAllForUser_Call struct {
	*mock.Call
}

// DeleteAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *RefreshTokenRepository_Expecter) DeleteAllForUser(ctx interface{}, userID interface{}) *RefreshTokenRepository_DeleteAllForUser_Call {
	return &RefreshTokenRepository_DeleteAllForUser_Call{Call: _e.mock.On("DeleteAllForUser", ctx, userID)}
}

func (_c *RefreshTokenRepository_DeleteAllForUser_Call) Run(run func(ctx context.Context, userID int64)) *RefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *RefreshTokenRepository_DeleteAllForUser_Call) Return(_a0 error) *RefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_DeleteAllForUser_Call) RunAndReturn(run func(context.Context, int64) error) *RefreshTokenRepository_DeleteAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPlainText provides a mock function with given fields: ctx, refreshTokenPlainText
func (_m *RefreshTokenRepository) GetByPlainText(ctx context.Context, refreshTokenPlainText string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, refreshTokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for GetByPlainText")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, refreshTokenPlainText)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, refreshTokenPlainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshTokenPlainText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_GetByPlainText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPlainText'
type RefreshTokenRepository_GetByPlainText_Call struct {
	*mock.Call
}

// GetByPlainText is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenPlainText string
func (_e *RefreshTokenRepository_Expecter) GetByPlainText(ctx interface{}, refreshTokenPlainText interface{}) *RefreshTokenRepository_GetByPlainText_Call {
	return &RefreshTokenRepository_GetByPlainText_Call{Call: _e.mock.On("GetByPlainText", ctx, refreshTokenPlainText)}
}

func (_c *RefreshTokenRepository_GetByPlainText_Call) Run(run func(ctx context.Context, refreshTokenPlainText string)) *RefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_GetByPlainText_Call) Return(_a0 *domain.RefreshToken, _a1 error) *RefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_GetByPlainText_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *RefreshTokenRepository_GetByPlainText_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, token
func (_m *RefreshTokenRepository) Insert(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type RefreshTokenRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Insert(ctx interface{}, token interface{}) *RefreshTokenRepository_Insert_Call {
	return &RefreshTokenRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, token)}
}

func (_c *RefreshTokenRepository_Insert_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *RefreshTokenRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Insert_Call) Return(_a0 error) *RefreshTokenRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_Insert_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *RefreshTokenRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByFamily provides a mock function with given fields: ctx, familyID
func (_m *RefreshTokenRepository) RevokeByFamily(ctx context.Context, familyID string) error {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_RevokeByFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByFamily'
type RefreshTokenRepository_RevokeByFamily_Call struct {
	*mock.Call
}

// RevokeByFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID string
func (_e *RefreshTokenRepository_Expecter) RevokeByFamily(ctx interface{}, familyID interface{}) *RefreshTokenRepository_RevokeByFamily_Call {
	return &RefreshTokenRepository_RevokeByFamily_Call{Call: _e.mock.On("RevokeByFamily", ctx, familyID)}
}

func (_c *RefreshTokenRepository_RevokeByFamily_Call) Run(run func(ctx context.Context, familyID string)) *RefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByFamily_Call) Return(_a0 error) *RefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByFamily_Call) RunAndReturn(run func(context.Context, string) error) *RefreshTokenRepository_RevokeByFamily_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByHash provides a mock function with given fields: ctx, hash
func (_m *RefreshTokenRepository) RevokeByHash(ctx context.Context, hash []byte) error {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type RefreshTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash []byte
func (_e *RefreshTokenRepository_Expecter) RevokeByHash(ctx interface{}, hash interface{}) *RefreshTokenRepository_RevokeByHash_Call {
	return &RefreshTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", ctx, hash)}
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Run(run func(ctx context.Context, hash []byte)) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) Return(_a0 error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByHash_Call) RunAndReturn(run func(context.Context, []byte) error) *RefreshTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function with given fields: ctx, oldRefreshToken, newRefreshToken
func (_m *RefreshTokenRepository) Rotate(ctx context.Context, oldRefreshToken *domain.RefreshToken, newRefreshToken *domain.RefreshToken) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, oldRefreshToken, newRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) (*domain.RefreshToken, error)); ok {
		return rf(ctx, oldRefreshToken, newRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) *domain.RefreshToken); ok {
		r0 = rf(ctx, oldRefreshToken, newRefreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.RefreshToken, *domain.RefreshToken) error); ok {
		r1 = rf(ctx, oldRefreshToken, newRefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type RefreshTokenRepository_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
//   - oldRefreshToken *domain.RefreshToken
//   - newRefreshToken *domain.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Rotate(ctx interface{}, oldRefreshToken interface{}, newRefreshToken interface{}) *RefreshTokenRepository_Rotate_Call {
	return &RefreshTokenRepository_Rotate_Call{Call: _e.mock.On("Rotate", ctx, oldRefreshToken, newRefreshToken)}
}

func (_c *RefreshTokenRepository_Rotate_Call) Run(run func(ctx context.Context, oldRefreshToken *domain.RefreshToken, newRefreshToken *domain.RefreshToken)) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken), args[2].(*domain.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Rotate_Call) Return(_a0 *domain.RefreshToken, _a1 error) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_Rotate_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken, *domain.RefreshToken) (*domain.RefreshToken, error)) *RefreshTokenRepository_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
