// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refreshtoken.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (hash, user_id, expires_at, family_id)
    VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	Hash      []byte             `json:"hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	FamilyID  pgtype.UUID        `json:"family_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Hash,
		arg.UserID,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
    OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    hash,
    user_id,
    expires_at,
    created_at,
    revoked_at,
    family_id,
    replaced_by_hash
FROM
    refresh_tokens
WHERE
    hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, hash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, hash)
	var i RefreshToken
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.FamilyID,
		&i.ReplacedByHash,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE
    refresh_tokens
SET
    revoked_at = NOW()
WHERE
    hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, hash)
	return err
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE
    refresh_tokens
SET
    revoked_at = NOW()
WHERE
    family_id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, familyID)
	return err
}

const setTokenReplacement = `-- name: SetTokenReplacement :exec
UPDATE
    refresh_tokens
SET
    replaced_by_hash = $2
WHERE
    hash = $1
`

type SetTokenReplacementParams struct {
	Hash           []byte `json:"hash"`
	ReplacedByHash []byte `json:"replaced_by_hash"`
}

func (q *Queries) SetTokenReplacement(ctx context.Context, arg SetTokenReplacementParams) error {
	_, err := q.db.Exec(ctx, setTokenReplacement, arg.Hash, arg.ReplacedByHash)
	return err
}
