// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
    VALUES ($1, $2, $3)
RETURNING
    id, username, email, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    email,
    password_hash,
    shuffles_remaining,
    last_shuffle_reset,
    created_at
FROM
    users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      []byte             `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id,
    username,
    email,
    password_hash,
    shuffles_remaining,
    last_shuffle_reset,
    created_at
FROM
    users
WHERE
    id = $1
`

type GetUserByIdRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      []byte             `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserShuffleReset = `-- name: UpdateUserShuffleReset :exec
UPDATE
    users
SET
    shuffles_remaining = 3,
    last_shuffle_reset = NOW()
WHERE
    id = $1
`

func (q *Queries) UpdateUserShuffleReset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserShuffleReset, id)
	return err
}
