// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_pool.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserGrid = `-- name: ClearUserGrid :exec
DELETE FROM daily_pools
WHERE
    user_id = $1
    AND assigned_at::date = CURRENT_DATE
`

func (q *Queries) ClearUserGrid(ctx context.Context, userID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearUserGrid, userID)
	return err
}

const getUserGrid = `-- name: GetUserGrid :many
SELECT
    dp.slot_number,
    dp.is_revealed,
    m.id AS movie_id,
    m.tmdb_id,
    m.vague_description,
    m.genres
FROM daily_pools AS dp
INNER JOIN movies AS m ON dp.movie_id = m.id
WHERE
    dp.user_id = $1
    AND dp.assigned_at::date = CURRENT_DATE
ORDER BY dp.slot_number
`

type GetUserGridRow struct {
	SlotNumber       int32    `json:"slot_number"`
	IsRevealed       bool     `json:"is_revealed"`
	MovieID          int64    `json:"movie_id"`
	TmdbID           int32    `json:"tmdb_id"`
	VagueDescription string   `json:"vague_description"`
	Genres           []string `json:"genres"`
}

func (q *Queries) GetUserGrid(ctx context.Context, userID pgtype.Int8) ([]GetUserGridRow, error) {
	rows, err := q.db.Query(ctx, getUserGrid, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserGridRow{}
	for rows.Next() {
		var i GetUserGridRow
		if err := rows.Scan(
			&i.SlotNumber,
			&i.IsRevealed,
			&i.MovieID,
			&i.TmdbID,
			&i.VagueDescription,
			&i.Genres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGridSlot = `-- name: InsertGridSlot :exec
INSERT INTO daily_pools (user_id, movie_id, slot_number)
VALUES ($1, $2, $3)
`

type InsertGridSlotParams struct {
	UserID     pgtype.Int8 `json:"user_id"`
	MovieID    pgtype.Int8 `json:"movie_id"`
	SlotNumber int32       `json:"slot_number"`
}

func (q *Queries) InsertGridSlot(ctx context.Context, arg InsertGridSlotParams) error {
	_, err := q.db.Exec(ctx, insertGridSlot, arg.UserID, arg.MovieID, arg.SlotNumber)
	return err
}
