// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genres.sql

package queries

import (
	"context"
)

const listGenres = `-- name: ListGenres :many
SELECT
    id,
    name
FROM genres
ORDER BY name ASC
`

func (q *Queries) ListGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Genre{}
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGenre = `-- name: UpsertGenre :exec
INSERT INTO genres (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
    SET name = excluded.name
`

type UpsertGenreParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpsertGenre(ctx context.Context, arg UpsertGenreParams) error {
	_, err := q.db.Exec(ctx, upsertGenre, arg.ID, arg.Name)
	return err
}
