// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/yaredow/glimpse-api/internal/types"
)

type DailyPool struct {
	ID         int64              `json:"id"`
	UserID     pgtype.Int8        `json:"user_id"`
	MovieID    pgtype.Int8        `json:"movie_id"`
	SlotNumber int32              `json:"slot_number"`
	IsRevealed bool               `json:"is_revealed"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type Movie struct {
	ID               int64              `json:"id"`
	TmdbID           int32              `json:"tmdb_id"`
	ImdbID           pgtype.Text        `json:"imdb_id"`
	VagueDescription string             `json:"vague_description"`
	Genres           []string           `json:"genres"`
	Title            string             `json:"title"`
	OriginalTitle    string             `json:"original_title"`
	FullSynopsis     string             `json:"full_synopsis"`
	PosterPath       pgtype.Text        `json:"poster_path"`
	BackdropPath     pgtype.Text        `json:"backdrop_path"`
	ReleaseDate      pgtype.Date        `json:"release_date"`
	Runtime          int32              `json:"runtime"`
	VoteAverage      pgtype.Numeric     `json:"vote_average"`
	VoteCount        int32              `json:"vote_count"`
	OriginalLanguage string             `json:"original_language"`
	Popularity       pgtype.Numeric     `json:"popularity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	Hash           []byte             `json:"hash"`
	UserID         int64              `json:"user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	FamilyID       pgtype.UUID        `json:"family_id"`
	ReplacedByHash []byte             `json:"replaced_by_hash"`
}

type Token struct {
	Hash   []byte             `json:"hash"`
	UserID int64              `json:"user_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
	Scope  string             `json:"scope"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      types.Password     `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Activated         bool               `json:"activated"`
}

type UserMovie struct {
	UserID    int64              `json:"user_id"`
	MovieID   int64              `json:"movie_id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
