// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movie.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFilteredMovies = `-- name: GetFilteredMovies :many
SELECT
    id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
FROM
    movies
WHERE
    (cardinality($1::text[]) = 0 OR genres && $1::text[])
    AND NOT genres && $2::text[]
    AND (cardinality($3::text[]) = 0 OR original_language = ANY ($3::text[]))
    AND vote_average >= $4
    AND EXTRACT(YEAR FROM release_date) BETWEEN $5::int AND $6::int
    AND id NOT IN (
        SELECT movie_id FROM user_movies WHERE user_id = $7
    )
ORDER BY
    popularity DESC
LIMIT $8
`

type GetFilteredMoviesParams struct {
	FavoriteGenres []string       `json:"favorite_genres"`
	ExcludedGenres []string       `json:"excluded_genres"`
	Languages      []string       `json:"languages"`
	MinRating      pgtype.Numeric `json:"min_rating"`
	MinYear        int32          `json:"min_year"`
	MaxYear        int32          `json:"max_year"`
	UserID         int64          `json:"user_id"`
	Limit          int32          `json:"limit"`
}

func (q *Queries) GetFilteredMovies(ctx context.Context, arg GetFilteredMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getFilteredMovies,
		arg.FavoriteGenres,
		arg.ExcludedGenres,
		arg.Languages,
		arg.MinRating,
		arg.MinYear,
		arg.MaxYear,
		arg.UserID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.ImdbID,
			&i.VagueDescription,
			&i.Genres,
			&i.Title,
			&i.OriginalTitle,
			&i.FullSynopsis,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ReleaseDate,
			&i.Runtime,
			&i.VoteAverage,
			&i.VoteCount,
			&i.OriginalLanguage,
			&i.Popularity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieByID = `-- name: GetMovieByID :one
SELECT
    id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
FROM
    movies
WHERE
    id = $1
`

func (q *Queries) GetMovieByID(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.VagueDescription,
		&i.Genres,
		&i.Title,
		&i.OriginalTitle,
		&i.FullSynopsis,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ReleaseDate,
		&i.Runtime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.OriginalLanguage,
		&i.Popularity,
		&i.CreatedAt,
	)
	return i, err
}

const getMovieByTMDBID = `-- name: GetMovieByTMDBID :one
SELECT
    id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
FROM
    movies
WHERE
    tmdb_id = $1
`

func (q *Queries) GetMovieByTMDBID(ctx context.Context, tmdbID int32) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByTMDBID, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.VagueDescription,
		&i.Genres,
		&i.Title,
		&i.OriginalTitle,
		&i.FullSynopsis,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ReleaseDate,
		&i.Runtime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.OriginalLanguage,
		&i.Popularity,
		&i.CreatedAt,
	)
	return i, err
}

const getMoviesByGenre = `-- name: GetMoviesByGenre :many
SELECT
    id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
FROM
    movies
WHERE
    $1 = ANY (genres)
ORDER BY
    popularity DESC
LIMIT $2
`

type GetMoviesByGenreParams struct {
	Genres []string `json:"genres"`
	Limit  int32    `json:"limit"`
}

func (q *Queries) GetMoviesByGenre(ctx context.Context, arg GetMoviesByGenreParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, getMoviesByGenre, arg.Genres, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.ImdbID,
			&i.VagueDescription,
			&i.Genres,
			&i.Title,
			&i.OriginalTitle,
			&i.FullSynopsis,
			&i.PosterPath,
			&i.BackdropPath,
			&i.ReleaseDate,
			&i.Runtime,
			&i.VoteAverage,
			&i.VoteCount,
			&i.OriginalLanguage,
			&i.Popularity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMoviePopularity = `-- name: UpdateMoviePopularity :one
UPDATE
    movies
SET
    popularity = $2
WHERE
    tmdb_id = $1
RETURNING
    id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
`

type UpdateMoviePopularityParams struct {
	TmdbID     int32          `json:"tmdb_id"`
	Popularity pgtype.Numeric `json:"popularity"`
}

func (q *Queries) UpdateMoviePopularity(ctx context.Context, arg UpdateMoviePopularityParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMoviePopularity, arg.TmdbID, arg.Popularity)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.VagueDescription,
		&i.Genres,
		&i.Title,
		&i.OriginalTitle,
		&i.FullSynopsis,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ReleaseDate,
		&i.Runtime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.OriginalLanguage,
		&i.Popularity,
		&i.CreatedAt,
	)
	return i, err
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (tmdb_id) DO UPDATE SET
    popularity    = EXCLUDED.popularity,
    vote_average  = EXCLUDED.vote_average,
    vote_count    = EXCLUDED.vote_count,
    poster_path   = EXCLUDED.poster_path,
    backdrop_path = EXCLUDED.backdrop_path
RETURNING id, tmdb_id, imdb_id, vague_description, genres, title, original_title, full_synopsis, poster_path, backdrop_path, release_date, runtime, vote_average, vote_count, original_language, popularity, created_at
`

type UpsertMovieParams struct {
	TmdbID           int32          `json:"tmdb_id"`
	ImdbID           pgtype.Text    `json:"imdb_id"`
	VagueDescription string         `json:"vague_description"`
	Genres           []string       `json:"genres"`
	Title            string         `json:"title"`
	OriginalTitle    string         `json:"original_title"`
	FullSynopsis     string         `json:"full_synopsis"`
	PosterPath       pgtype.Text    `json:"poster_path"`
	BackdropPath     pgtype.Text    `json:"backdrop_path"`
	ReleaseDate      pgtype.Date    `json:"release_date"`
	Runtime          int32          `json:"runtime"`
	VoteAverage      pgtype.Numeric `json:"vote_average"`
	VoteCount        int32          `json:"vote_count"`
	OriginalLanguage string         `json:"original_language"`
	Popularity       pgtype.Numeric `json:"popularity"`
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, upsertMovie,
		arg.TmdbID,
		arg.ImdbID,
		arg.VagueDescription,
		arg.Genres,
		arg.Title,
		arg.OriginalTitle,
		arg.FullSynopsis,
		arg.PosterPath,
		arg.BackdropPath,
		arg.ReleaseDate,
		arg.Runtime,
		arg.VoteAverage,
		arg.VoteCount,
		arg.OriginalLanguage,
		arg.Popularity,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.VagueDescription,
		&i.Genres,
		&i.Title,
		&i.OriginalTitle,
		&i.FullSynopsis,
		&i.PosterPath,
		&i.BackdropPath,
		&i.ReleaseDate,
		&i.Runtime,
		&i.VoteAverage,
		&i.VoteCount,
		&i.OriginalLanguage,
		&i.Popularity,
		&i.CreatedAt,
	)
	return i, err
}
