// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteTokensForUser(ctx context.Context, arg DeleteTokensForUserParams) error
	GetFilteredMovies(ctx context.Context, arg GetFilteredMoviesParams) ([]Movie, error)
	GetMovieByID(ctx context.Context, id int64) (Movie, error)
	GetMovieByTMDBID(ctx context.Context, tmdbID int32) (Movie, error)
	GetMoviesByGenre(ctx context.Context, arg GetMoviesByGenreParams) ([]Movie, error)
	GetRefreshToken(ctx context.Context, hash []byte) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByToken(ctx context.Context, arg GetUserByTokenParams) (User, error)
	GetUserPreference(ctx context.Context, userID int64) (UserPreference, error)
	ListGenres(ctx context.Context) ([]Genre, error)
	RevokeRefreshToken(ctx context.Context, hash []byte) (int64, error)
	RevokeTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	SetTokenReplacement(ctx context.Context, arg SetTokenReplacementParams) error
	UpdateMoviePopularity(ctx context.Context, arg UpdateMoviePopularityParams) (Movie, error)
	UpdateOnboardingStatus(ctx context.Context, arg UpdateOnboardingStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserShuffleReset(ctx context.Context, id int64) error
	UpsertGenre(ctx context.Context, arg UpsertGenreParams) error
	UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error)
	UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (UserPreference, error)
}

var _ Querier = (*Queries)(nil)
