// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (hash, user_id, expiry, scope)
VALUES ($1, $2, $3, $4)
`

type CreateTokenParams struct {
	Hash   []byte             `json:"hash"`
	UserID int64              `json:"user_id"`
	Expiry pgtype.Timestamptz `json:"expiry"`
	Scope  string             `json:"scope"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.Exec(ctx, createToken,
		arg.Hash,
		arg.UserID,
		arg.Expiry,
		arg.Scope,
	)
	return err
}

const deleteTokensForUser = `-- name: DeleteTokensForUser :exec
DELETE FROM tokens
WHERE
    user_id = $1
    AND scope = $2
`

type DeleteTokensForUserParams struct {
	UserID int64  `json:"user_id"`
	Scope  string `json:"scope"`
}

func (q *Queries) DeleteTokensForUser(ctx context.Context, arg DeleteTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteTokensForUser, arg.UserID, arg.Scope)
	return err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT
    u.id,
    u.username,
    u.email,
    u.password_hash,
    u.shuffles_remaining,
    u.last_shuffle_reset,
    u.created_at,
    u.activated,
    u.version
FROM
    tokens AS t
INNER JOIN users AS u ON t.user_id = u.id
WHERE
    t.hash = $1
    AND t.scope = $2
    AND t.expiry > NOW()
`

type GetUserByTokenParams struct {
	Hash  []byte `json:"hash"`
	Scope string `json:"scope"`
}

func (q *Queries) GetUserByToken(ctx context.Context, arg GetUserByTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByToken, arg.Hash, arg.Scope)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.CreatedAt,
		&i.Activated,
		&i.Version,
	)
	return i, err
}
