// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_interactions.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInteractionsForUser = `-- name: GetInteractionsForUser :many
SELECT id, user_id, movie_id, action, grid_session_id, grid_position, reveal_to_action_ms, acted_at FROM user_interactions
WHERE user_id = $1
ORDER BY acted_at DESC
LIMIT $2
`

type GetInteractionsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetInteractionsForUser(ctx context.Context, arg GetInteractionsForUserParams) ([]UserInteraction, error) {
	rows, err := q.db.Query(ctx, getInteractionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInteraction{}
	for rows.Next() {
		var i UserInteraction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MovieID,
			&i.Action,
			&i.GridSessionID,
			&i.GridPosition,
			&i.RevealToActionMs,
			&i.ActedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActionedMovieIDs = `-- name: GetUserActionedMovieIDs :many
SELECT DISTINCT movie_id FROM user_interactions
WHERE user_id = $1 AND action IN ('watched', 'skipped')
`

func (q *Queries) GetUserActionedMovieIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getUserActionedMovieIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var movie_id int64
		if err := rows.Scan(&movie_id); err != nil {
			return nil, err
		}
		items = append(items, movie_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInteraction = `-- name: InsertInteraction :exec
INSERT INTO user_interactions (
    user_id,
    movie_id,
    action,
    grid_session_id,
    grid_position,
    reveal_to_action_ms,
    acted_at
)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type InsertInteractionParams struct {
	UserID           int64       `json:"user_id"`
	MovieID          int64       `json:"movie_id"`
	Action           ActionType  `json:"action"`
	GridSessionID    uuid.UUID   `json:"grid_session_id"`
	GridPosition     pgtype.Int4 `json:"grid_position"`
	RevealToActionMs pgtype.Int4 `json:"reveal_to_action_ms"`
}

func (q *Queries) InsertInteraction(ctx context.Context, arg InsertInteractionParams) error {
	_, err := q.db.Exec(ctx, insertInteraction,
		arg.UserID,
		arg.MovieID,
		arg.Action,
		arg.GridSessionID,
		arg.GridPosition,
		arg.RevealToActionMs,
	)
	return err
}
