// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/yaredow/glimpse-api/internal/types"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING
    id, username, email, created_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash types.Password `json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    email,
    password_hash,
    shuffles_remaining,
    last_shuffle_reset,
    exploration_rate,
    total_interactions,
    created_at,
    activated,
    version
FROM
    users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      types.Password     `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	ExplorationRate   float64            `json:"exploration_rate"`
	TotalInteractions int32              `json:"total_interactions"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Activated         bool               `json:"activated"`
	Version           int32              `json:"version"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.ExplorationRate,
		&i.TotalInteractions,
		&i.CreatedAt,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
    id,
    username,
    email,
    password_hash,
    shuffles_remaining,
    last_shuffle_reset,
    exploration_rate,
    total_interactions,
    created_at,
    activated,
    version
FROM
    users
WHERE
    id = $1
`

type GetUserByIdRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      types.Password     `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	ExplorationRate   float64            `json:"exploration_rate"`
	TotalInteractions int32              `json:"total_interactions"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Activated         bool               `json:"activated"`
	Version           int32              `json:"version"`
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.ExplorationRate,
		&i.TotalInteractions,
		&i.CreatedAt,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    username = $2,
    email = $3,
    password_hash = $4,
    activated = $5,
    version = version + 1
WHERE
    id = $1 AND version = $6
RETURNING
    id, username, email, password_hash, shuffles_remaining, last_shuffle_reset, created_at, activated, version
`

type UpdateUserParams struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash types.Password `json:"password_hash"`
	Activated    bool           `json:"activated"`
	Version      int32          `json:"version"`
}

type UpdateUserRow struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	PasswordHash      types.Password     `json:"password_hash"`
	ShufflesRemaining int32              `json:"shuffles_remaining"`
	LastShuffleReset  pgtype.Timestamptz `json:"last_shuffle_reset"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Activated         bool               `json:"activated"`
	Version           int32              `json:"version"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Activated,
		arg.Version,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ShufflesRemaining,
		&i.LastShuffleReset,
		&i.CreatedAt,
		&i.Activated,
		&i.Version,
	)
	return i, err
}

const updateUserInteractionStats = `-- name: UpdateUserInteractionStats :exec
UPDATE users
SET total_interactions = total_interactions + 1,
    exploration_rate = GREATEST(0.05, 0.4 * EXP(-CAST(total_interactions + 1 AS FLOAT) / 50.0))
WHERE id = $1
`

func (q *Queries) UpdateUserInteractionStats(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserInteractionStats, id)
	return err
}

const updateUserShuffleReset = `-- name: UpdateUserShuffleReset :exec
UPDATE
    users
SET
    shuffles_remaining = 3,
    last_shuffle_reset = NOW()
WHERE
    id = $1
`

func (q *Queries) UpdateUserShuffleReset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserShuffleReset, id)
	return err
}
