// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_affinities.sql

package queries

import (
	"context"
)

const decayAffinies = `-- name: DecayAffinies :exec
UPDATE user_affinities
SET score = score * 0.97
`

func (q *Queries) DecayAffinies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, decayAffinies)
	return err
}

const getUserAffinities = `-- name: GetUserAffinities :many
SELECT user_id, dimension, value, score, confidence, last_updated FROM user_affinities
WHERE user_id = $1
`

func (q *Queries) GetUserAffinities(ctx context.Context, userID int64) ([]UserAffinity, error) {
	rows, err := q.db.Query(ctx, getUserAffinities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAffinity{}
	for rows.Next() {
		var i UserAffinity
		if err := rows.Scan(
			&i.UserID,
			&i.Dimension,
			&i.Value,
			&i.Score,
			&i.Confidence,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAffinity = `-- name: UpsertUserAffinity :exec
INSERT INTO user_affinities (
    user_id, dimension, value, score, confidence, last_updated
)
VALUES ($1, $2, $3, $4, 1, NOW())
ON CONFLICT (user_id, dimension, value) DO UPDATE SET
    score        = user_affinities.score + excluded.score,
    confidence   = user_affinities.confidence + 1,
    last_updated = NOW()
`

type UpsertUserAffinityParams struct {
	UserID    int64   `json:"user_id"`
	Dimension string  `json:"dimension"`
	Value     string  `json:"value"`
	Score     float64 `json:"score"`
}

func (q *Queries) UpsertUserAffinity(ctx context.Context, arg UpsertUserAffinityParams) error {
	_, err := q.db.Exec(ctx, upsertUserAffinity,
		arg.UserID,
		arg.Dimension,
		arg.Value,
		arg.Score,
	)
	return err
}
