version: 3
workdir: .
allow:
  depOnAnyVendor: true

components:
  cmd:
    in: cmd/**
  handlerbase:
    in: internal/handler
  handler:
    in: internal/handler/**
  usecase:
    in: internal/usecase/**
  repository:
    in: internal/repository/**
  entity:
    in: internal/entity
  worker:
    in: internal/worker/**
  auth:
    in: internal/auth
  db:
    in: internal/db
  mailer:
    in: internal/mailer
  sqlc:
    in: internal/sqlc/**

commonComponents:
  - entity

deps:
  cmd:
    anyProjectDeps: true
  handlerbase:
    mayDependOn:
      - usecase
      - auth
  handler:
    mayDependOn:
      - usecase
      - auth
      - handlerbase
  repository:
    mayDependOn:
      - usecase
      - sqlc
  worker:
    mayDependOn:
      - repository
      - entity

excludeFiles:
  - "^.*_test\\.go$"
  - "vendor/"
